### ISSUE TITLE
Missing property `redirect_uris`

### ISSUE THREAD

**Issue by BenoitDuffez** [yannrouillard/gphotos-sync#2]
Your project looks VERY interesting. However I wasn't able to have it download all the photos. Heres the output of `gphotos-sync download ~/whatever/`:

```
Traceback (most recent call last):
  File "/usr/local/bin/gphotos-sync", line 395, in <module>
    credentials_file=credentials_file)
  File "/usr/local/bin/gphotos-sync", line 194, in __init__
    self.gauth.CommandLineAuth()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 67, in _decorated
    self.GetFlow()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 345, in GetFlow
    self.LoadClientConfig()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 294, in LoadClientConfig
    self.LoadClientConfigFile()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 314, in LoadClientConfigFile
    raise InvalidConfigError('Invalid client secrets file %s' % error)
pydrive.settings.InvalidConfigError: Invalid client secrets file Missing property "redirect_uris" in a client type of "web".
```

Here's the contents of my `~/.config/gphotos-sync/client_secret.json`:

    {"web":{"client_id":"xxx-yyy.apps.googleusercontent.com","project_id":"photossync-nnnn","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"zzzzzzz"}}

Did I do something wrong?

**Comment by BenoitDuffez** [comment]
Wrong OAuth type. Sorry.

**Comment by MegaMind77-coder** [comment]
whats the error can smeone pls help??

**Comment by enobufs** [comment]
@MegaMind77-coder I guess his client_secret.json did not have redirect_uris. I just had the same error, because I downloaded json credential file from Google API console without entering "Authorized redirect URIs".
