### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by jrhutchins** [yannrouillard/gphotos-sync#5]
After downloading the project as a .zip and unzipping, I get the following error:

Installed /home/jonathan/gphotos-sync-master/pbr-3.0.0-py2.7.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/jonathan/gphotos-sync-master/pbr-3.0.0-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/jonathan/gphotos-sync-master/pbr-3.0.0-py2.7.egg/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/jonathan/gphotos-sync-master/pbr-3.0.0-py2.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/jonathan/gphotos-sync-master/pbr-3.0.0-py2.7.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/jonathan/gphotos-sync-master/pbr-3.0.0-py2.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/jonathan/gphotos-sync-master/pbr-3.0.0-py2.7.egg/pbr/packaging.py", line 748, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gphotos-sync was given, but was not able to be found.
error in setup command: Error parsing /home/jonathan/gphotos-sync-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gphotos-sync was given, but was not able to be found.

**Comment by yannrouillard** [comment]
Hi @jrhutchins,

Not sure about your exact issue but I hope you found a solution since you reported the ticket !

Anyway, I don't maintain this project anymore so I will close this bug.
If you are still interested in such a tool, I recommend you have a look at https://github.com/gilesknap/gphotos-sync which is a fork of this project with considerable changes to improve it.
